extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier

env:
  browser: true
  es6: true
  jest: true

plugins:
  - "@typescript-eslint"
  - react
  - prettier

rules:
  prettier/prettier: error

settings:
  react:
    pragma: "React"
    version: "detect"

parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"