env:
  browser: true
  es2021: true
  jest: true

extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - airbnb
  - airbnb/hooks
  - airbnb-typescript

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'

plugins:
  - react
  - '@typescript-eslint'

rules:
  no-console: 'off'
  no-param-reassign: ['error', { 'props': false }]
  no-void: 'off'
