env:
  browser: true
  es2021: true
  jest: true

extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb

overrides:
  - {
      files: ['*.tsx'],
      rules: { 'no-undef': 'off' }
    }

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

rules:
  'import/extensions': [
    'error',
    'ignorePackages', {
      'ts': 'never',
      'tsx': 'never'
    }
  ]
  no-param-reassign: ['error', { 'props': false }]
  no-use-before-define: 'off'
  'react/jsx-filename-extension': [ 'warn', {'extensions': ['.tsx']} ]
  '@typescript-eslint/no-use-before-define': ['error']

settings:
  import/resolver:
    typescript: {}